import { f, type SubcategoryProfile } from "./types";

export const PROFILES: SubcategoryProfile[] = [
  // ---------------- Correspondence & Communication ----------------
  {
    subcategoryId: "internal-memos",
    docKind: "memo",
    noun: "Internal Memo",
    purpose: "shares a short internal update or instruction with staff or a team",
    flavors: ["Team", "Department-Wide", "Company-Wide", "Manager-to-Staff", "Cross-Team", "Policy Update", "Reminder", "Follow-Up", "Kickoff", "Wrap-Up", "Urgent"],
  },
  {
    subcategoryId: "formal-letters",
    docKind: "letter",
    noun: "Formal Business Letter",
    purpose: "communicates an official message to a client, partner, or outside official",
    flavors: ["Client-Facing", "Partner", "Government", "Vendor", "Introductory", "Follow-Up", "Confirmation", "Congratulatory", "Formal Request", "Formal Response", "Closing"],
  },
  {
    subcategoryId: "email-templates",
    docKind: "memo",
    noun: "Email Template",
    purpose: "gives a ready-made structure for a common business email",
    flavors: ["Follow-Up", "Introduction", "Meeting Request", "Status Update", "Apology", "Reminder", "Thank-You", "Cold Outreach", "Internal Update", "Escalation", "Closing the Loop"],
  },
  {
    subcategoryId: "announcements",
    docKind: "notice",
    noun: "Internal Announcement",
    purpose: "announces company or team news to employees",
    flavors: ["New Hire", "Promotion", "Reorg", "Product Launch", "Policy Change", "Office Event", "Milestone", "Leadership Change", "Partnership", "Award", "General"],
  },
  {
    subcategoryId: "notices",
    docKind: "notice",
    noun: "General Notice",
    purpose: "formally notifies staff or the public of a change, closure, or reminder",
    flavors: ["Office Closure", "Schedule Change", "Maintenance", "Deadline Reminder", "Policy Reminder", "Safety", "Parking", "IT Downtime", "Weather", "Holiday Hours", "General"],
  },
  {
    subcategoryId: "cover-letters",
    docKind: "letter",
    noun: "Cover Letter",
    purpose: "introduces a candidate alongside a job application",
    extraFields: [f("position", "Position Applying For"), f("key_qualification", "Key Qualification to Highlight", "textarea", false)],
    flavors: ["Entry-Level", "Career Change", "Internal Transfer", "Referral", "Executive", "Freelance / Contract", "Internship", "Post-Interview Follow-Up", "Unsolicited", "Grant Application", "General"],
  },
  {
    subcategoryId: "thank-you-notes",
    docKind: "letter",
    noun: "Thank-You Note",
    purpose: "expresses professional thanks or appreciation",
    flavors: ["Post-Interview", "Client Appreciation", "Colleague Shoutout", "Vendor Thanks", "Mentor Thanks", "Team Thanks", "Event Follow-Up", "Referral Thanks", "Retirement", "Anniversary", "General"],
  },
  {
    subcategoryId: "meeting-invitations",
    docKind: "memo",
    noun: "Meeting Invitation",
    purpose: "invites recipients to a meeting with agenda and logistics",
    extraFields: [f("meeting_time", "Date & Time"), f("location", "Location / Link"), f("agenda", "Agenda", "textarea", false)],
    flavors: ["Team Sync", "Client Call", "All-Hands", "Board Meeting", "Interview", "Kickoff", "Planning Session", "Retrospective", "Training", "Vendor Meeting", "One-on-One"],
  },
  {
    subcategoryId: "reference-letters",
    docKind: "letter",
    noun: "Reference Letter",
    purpose: "recommends a person for a role, program, or opportunity",
    extraFields: [f("relationship", "Relationship to Candidate"), f("duration_known", "How Long You've Known Them", "text", false)],
    flavors: ["Job Reference", "Academic Reference", "Character Reference", "Landlord Reference", "Promotion Support", "Internal Transfer", "Volunteer Reference", "Internship Reference", "Contractor Reference", "Scholarship", "General"],
  },
  {
    subcategoryId: "press-correspondence",
    docKind: "letter",
    noun: "Press Correspondence",
    purpose: "communicates with a media contact on behalf of the company",
    extraFields: [f("outlet", "Media Outlet"), f("topic", "Topic")],
    flavors: ["Press Pitch", "Interview Response", "Correction Request", "Embargo Notice", "Media Statement", "Follow-Up", "Exclusive Offer", "Crisis Response", "Event Invitation", "Op-Ed Submission", "General"],
  },

  // ---------------- Human Resources ----------------
  {
    subcategoryId: "offer-letters",
    docKind: "letter",
    noun: "Offer Letter",
    purpose: "formally extends a job offer, confirming role, compensation, and start date",
    extraFields: [f("position", "Position Title"), f("salary", "Annual Salary", "currency"), f("start_date", "Start Date", "date")],
    flavors: ["Full-Time", "Part-Time", "Remote", "Internship", "Executive", "Fixed-Term Contract", "Internal Transfer", "Relocation-Included", "Sign-On Bonus", "Seasonal", "General"],
  },
  {
    subcategoryId: "performance-reviews",
    docKind: "report",
    noun: "Performance Review",
    purpose: "evaluates an employee's performance over a review period",
    extraFields: [f("employee_name", "Employee Name"), f("role", "Role / Title"), f("rating", "Overall Rating", "select", true, { options: ["Exceeds Expectations", "Meets Expectations", "Needs Improvement", "Unsatisfactory"] })],
    flavors: ["Annual", "Mid-Year", "Probationary", "90-Day", "Quarterly", "Manager", "Peer", "Self-Assessment", "Promotion", "Project-Based", "General"],
  },
  {
    subcategoryId: "onboarding",
    docKind: "checklist",
    noun: "Onboarding Checklist",
    purpose: "walks a new hire and their manager through the first days on the job",
    extraFields: [f("new_hire_name", "New Hire Name"), f("start_date", "Start Date", "date")],
    flavors: ["Full-Time", "Remote", "Contractor", "Executive", "Intern", "Manager-Level", "International", "Part-Time", "Seasonal", "Cross-Department Transfer", "General"],
  },
  {
    subcategoryId: "policy-documents",
    docKind: "notice",
    noun: "HR Policy Document",
    purpose: "communicates a company policy covering conduct, leave, or benefits",
    extraFields: [f("policy_owner", "Policy Owner", "text", false)],
    flavors: ["Code of Conduct", "Remote Work", "Leave & PTO", "Dress Code", "Anti-Harassment", "Social Media", "Expense", "Data Security", "Attendance", "Diversity & Inclusion", "General"],
  },
  {
    subcategoryId: "disciplinary",
    docKind: "form",
    noun: "Disciplinary Write-Up",
    purpose: "documents a policy violation and the corrective action taken",
    extraFields: [f("incident_date", "Incident Date", "date"), f("violation_type", "Type of Violation", "select", true, { options: ["Attendance", "Conduct", "Performance", "Policy Violation", "Safety", "Other"] })],
    flavors: ["Verbal Warning", "Written Warning", "Final Warning", "Attendance", "Conduct", "Safety Violation", "Performance", "Policy Breach", "Insubordination", "Second Offense", "General"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "Manager", detailsLabel: "Description of Incident" },
  },
  {
    subcategoryId: "exit-interviews",
    docKind: "form",
    noun: "Exit Interview",
    purpose: "captures a departing employee's feedback and offboarding details",
    extraFields: [f("last_day", "Last Day of Employment", "date"), f("reason_for_leaving", "Reason for Leaving", "select", true, { options: ["New Opportunity", "Relocation", "Compensation", "Management", "Career Change", "Retirement", "Other"] })],
    flavors: ["Voluntary Resignation", "Involuntary", "Retirement", "End of Contract", "Layoff", "Internal Transfer", "Remote Employee", "Executive", "Manager", "Short-Tenure", "General"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "HR Representative", detailsLabel: "Feedback" },
  },
  {
    subcategoryId: "leave-requests",
    docKind: "form",
    noun: "Leave Request",
    purpose: "requests approval for time off from work",
    extraFields: [f("start_date", "Start Date", "date"), f("end_date", "End Date", "date"), f("leave_type", "Leave Type", "select", true, { options: ["Vacation", "Sick", "Personal", "Bereavement", "Jury Duty", "Unpaid", "Other"] })],
    flavors: ["Vacation", "Sick Leave", "Parental Leave", "Bereavement", "Jury Duty", "Personal Day", "Unpaid Leave", "Medical Leave", "Sabbatical", "Military Leave", "General"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "Manager", detailsLabel: "Reason for Leave" },
  },
  {
    subcategoryId: "job-descriptions",
    docKind: "report",
    noun: "Job Description",
    purpose: "defines a role's responsibilities, requirements, and reporting line",
    extraFields: [f("job_title", "Job Title"), f("reports_to", "Reports To"), f("requirements", "Requirements", "textarea", false)],
    flavors: ["Entry-Level", "Mid-Level", "Senior", "Manager", "Executive", "Remote", "Contract", "Internship", "Seasonal", "Cross-Functional", "General"],
  },
  {
    subcategoryId: "employee-recognition",
    docKind: "letter",
    noun: "Employee Recognition Note",
    purpose: "formally recognizes an employee's achievement or contribution",
    extraFields: [f("achievement", "Achievement", "textarea", false)],
    flavors: ["Employee of the Month", "Work Anniversary", "Above and Beyond", "Team Player", "Innovation Award", "Peer Nomination", "Sales Milestone", "Perfect Attendance", "Leadership", "Customer Praise", "General"],
  },
  {
    subcategoryId: "benefits-enrollment",
    docKind: "form",
    noun: "Benefits Enrollment Form",
    purpose: "enrolls or updates an employee's benefits elections",
    extraFields: [f("plan_type", "Plan Type", "select", true, { options: ["Medical", "Dental", "Vision", "401(k)", "Life Insurance", "FSA/HSA", "Other"] }), f("effective_date", "Effective Date", "date")],
    flavors: ["New Hire Enrollment", "Open Enrollment", "Life Event Change", "Dependent Addition", "Plan Upgrade", "Opt-Out", "401(k) Election", "FSA Election", "COBRA Continuation", "Beneficiary Update", "General"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "Benefits Administrator", detailsLabel: "Elections / Notes" },
  },

  // ---------------- Finance & Accounting (expense-reports done by hand) ----------------
  {
    subcategoryId: "invoices",
    docKind: "invoice",
    noun: "Invoice",
    purpose: "bills a client for goods or services rendered",
    extraFields: [f("invoice_number", "Invoice #", "text", false)],
    flavors: ["Standard", "Recurring / Subscription", "Milestone-Based", "Retainer", "Time & Materials", "International", "Deposit / Prepayment", "Final Invoice", "Consolidated", "Overdue / Past-Due", "General"],
  },
  {
    subcategoryId: "budget-requests",
    docKind: "form",
    noun: "Budget Request",
    purpose: "requests approval for a new or expanded budget allocation",
    extraFields: [f("amount_requested", "Amount Requested", "currency"), f("budget_period", "Budget Period", "text", false, { placeholder: "e.g. FY2026" })],
    flavors: ["Departmental", "Project", "Headcount", "Marketing Campaign", "Capital Expenditure", "Software / Tooling", "Travel Budget", "Training Budget", "Emergency", "Annual Planning", "General"],
    overrides: { subjectLabel: "Requested By", approverLabel: "Finance Approver", detailsLabel: "Justification" },
  },
  {
    subcategoryId: "purchase-orders",
    docKind: "invoice",
    noun: "Purchase Order",
    purpose: "authorizes a purchase of goods or services from a vendor",
    extraFields: [f("po_number", "PO Number", "text", false)],
    flavors: ["Standard", "Blanket", "Rush", "Services", "Capital Equipment", "Recurring", "International", "Drop-Ship", "Contract Release", "Amendment", "General"],
    overrides: { counterpartyLabel: "Vendor", totalLabel: "Total Order Amount" },
  },
  {
    subcategoryId: "reimbursement-forms",
    docKind: "form",
    noun: "Reimbursement Form",
    purpose: "requests reimbursement for an out-of-pocket business cost",
    extraFields: [f("amount", "Amount", "currency"), f("category", "Category", "select", true, { options: ["Supplies", "Travel", "Meals", "Subscriptions", "Equipment", "Other"] })],
    flavors: ["General", "Software Subscription", "Professional Membership", "Certification Fee", "Tuition", "Relocation-Related", "Client Gift", "Emergency Purchase", "Mileage-Adjacent", "Recurring", "Miscellaneous"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "Manager", detailsLabel: "Description" },
  },
  {
    subcategoryId: "financial-statements",
    docKind: "report",
    noun: "Financial Statement Summary",
    purpose: "summarizes the company or department's financial position for internal review",
    extraFields: [f("period_covered", "Period Covered", "text", false)],
    flavors: ["Monthly", "Quarterly", "Annual", "Departmental", "Cash Flow", "Profit & Loss", "Balance Sheet", "Board-Ready", "Investor Update", "Forecast vs Actual", "General"],
    overrides: { includePeriod: false },
  },
  {
    subcategoryId: "payroll-forms",
    docKind: "form",
    noun: "Payroll Adjustment Form",
    purpose: "documents a change to an employee's payroll processing",
    extraFields: [f("effective_date", "Effective Date", "date"), f("adjustment_type", "Adjustment Type", "select", true, { options: ["Salary Change", "Bonus", "Correction", "Deduction Change", "Direct Deposit Update", "Other"] })],
    flavors: ["Salary Change", "Bonus Payout", "Commission", "Correction", "Deduction Update", "Direct Deposit Change", "Overtime Adjustment", "Retroactive Pay", "Garnishment", "Final Paycheck", "General"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "Payroll Manager", detailsLabel: "Details" },
  },
  {
    subcategoryId: "tax-forms",
    docKind: "form",
    noun: "Internal Tax Documentation",
    purpose: "records information needed for internal tax reporting or compliance",
    extraFields: [f("tax_year", "Tax Year", "text", false), f("form_type", "Related Form", "text", false, { placeholder: "e.g. W-9, 1099" })],
    flavors: ["Contractor Documentation", "Sales Tax Exemption", "Withholding Update", "Year-End Summary", "Multi-State Filing", "Nonprofit Status", "Vendor Tax Info", "Expense Deduction Log", "Depreciation Note", "Audit Prep", "General"],
    overrides: { subjectLabel: "Prepared For", approverLabel: "Finance Reviewer", detailsLabel: "Notes", includeDepartment: false },
  },
  {
    subcategoryId: "credit-memos",
    docKind: "invoice",
    noun: "Credit Memo",
    purpose: "issues a billing credit or adjustment to a customer's account",
    extraFields: [f("original_invoice", "Original Invoice #", "text", false), f("reason", "Reason for Credit", "text", false)],
    flavors: ["Overbilling Correction", "Returned Goods", "Service Credit", "Pricing Error", "Goodwill Credit", "Duplicate Payment", "Damaged Item", "Early Payment Discount", "Volume Rebate", "Contract Adjustment", "General"],
    overrides: { counterpartyLabel: "Customer", totalLabel: "Credit Amount", includeDueDate: false },
  },
  {
    subcategoryId: "audit-documentation",
    docKind: "report",
    noun: "Audit Documentation",
    purpose: "records findings and evidence prepared for an internal or external audit",
    extraFields: [f("audit_scope", "Audit Scope", "text", false)],
    flavors: ["Internal Controls", "Financial", "Compliance", "IT Systems", "Vendor", "Payroll", "Inventory", "Expense", "Year-End", "Follow-Up", "General"],
  },

  // ---------------- Legal & Compliance ----------------
  {
    subcategoryId: "ndas",
    docKind: "contract",
    noun: "Non-Disclosure Agreement",
    purpose: "protects confidential information shared between two parties",
    extraFields: [f("purpose_of_disclosure", "Purpose of Disclosure", "textarea", false)],
    flavors: ["Mutual", "One-Way", "Employee", "Contractor", "Vendor", "Investor", "Partnership Discussion", "M&A Due Diligence", "Client", "Interview Candidate", "General"],
    overrides: { partyALabel: "Disclosing Party", partyBLabel: "Receiving Party" },
  },
  {
    subcategoryId: "simple-contracts",
    docKind: "contract",
    noun: "Simple Service Agreement",
    purpose: "outlines a basic agreement for work or services between two parties",
    extraFields: [f("scope_of_work", "Scope of Work", "textarea", false)],
    flavors: ["Freelance", "Consulting", "Vendor Services", "Short-Term Project", "Retainer", "One-Time Service", "Equipment Rental", "Subcontractor", "Referral Agreement", "Maintenance Services", "General"],
  },
  {
    subcategoryId: "waivers",
    docKind: "form",
    noun: "Waiver & Release Form",
    purpose: "releases the company from liability for a specific activity or event",
    extraFields: [f("activity", "Activity / Event")],
    flavors: ["Event Participation", "Photo/Media Release", "Facility Use", "Volunteer", "Minor Participant", "Equipment Use", "Off-Site Activity", "Trial/Demo Use", "Health Screening", "Travel-Related", "General"],
    overrides: { subjectLabel: "Participant Name", approverLabel: "Company Representative", detailsLabel: "Terms of Release", includeDepartment: false },
  },
  {
    subcategoryId: "policy-acknowledgments",
    docKind: "form",
    noun: "Policy Acknowledgment",
    purpose: "documents that an employee has read and agreed to a company policy",
    extraFields: [f("policy_name", "Policy Name")],
    flavors: ["Code of Conduct", "Handbook", "IT Security", "Confidentiality", "Anti-Harassment", "Safety", "Remote Work", "Social Media", "Conflict of Interest", "Data Privacy", "General"],
    overrides: { subjectLabel: "Employee Name", approverLabel: "HR Representative", detailsLabel: "Acknowledgment Statement" },
  },
  {
    subcategoryId: "incident-liability",
    docKind: "form",
    noun: "Incident & Liability Report",
    purpose: "documents an incident with potential liability implications",
    extraFields: [f("incident_date", "Incident Date", "date"), f("location", "Location")],
    flavors: ["Workplace Injury", "Property Damage", "Visitor Incident", "Vehicle Incident", "Near-Miss", "Product Liability", "Slip and Fall", "Equipment Failure", "Third-Party Claim", "Security Incident", "General"],
    overrides: { subjectLabel: "Reported By", approverLabel: "Risk Manager", detailsLabel: "Description of Incident" },
  },
  {
    subcategoryId: "compliance-checklists",
    docKind: "checklist",
    noun: "Compliance Checklist",
    purpose: "verifies that regulatory or internal requirements have been met",
    extraFields: [f("regulation", "Regulation / Standard", "text", false)],
    flavors: ["Data Privacy", "Workplace Safety", "Financial Reporting", "Employment Law", "Environmental", "Industry Certification", "Vendor Compliance", "Anti-Bribery", "Accessibility", "Recordkeeping", "General"],
  },
  {
    subcategoryId: "data-privacy",
    docKind: "notice",
    noun: "Data Privacy Notice",
    purpose: "explains how personal data is collected, used, and protected",
    extraFields: [f("data_types", "Types of Data Covered", "textarea", false)],
    flavors: ["Customer-Facing", "Employee", "Website", "Vendor", "Cookie Notice", "Third-Party Sharing", "Data Breach Notification", "Retention Policy", "International Transfer", "Consent Update", "General"],
  },
  {
    subcategoryId: "licensing-agreements",
    docKind: "contract",
    noun: "Licensing Agreement",
    purpose: "grants rights to use intellectual property or software under agreed terms",
    extraFields: [f("licensed_property", "Licensed Property / Software")],
    flavors: ["Software License", "Trademark License", "Content License", "Franchise", "Patent License", "Distribution Rights", "White-Label", "Open Source Exception", "Renewal", "Territory-Limited", "General"],
    overrides: { partyALabel: "Licensor", partyBLabel: "Licensee" },
  },
  {
    subcategoryId: "regulatory-filings",
    docKind: "report",
    noun: "Regulatory Filing Summary",
    purpose: "summarizes information prepared for a regulatory filing",
    extraFields: [f("regulator", "Regulatory Body", "text", false), f("filing_deadline", "Filing Deadline", "date", false)],
    flavors: ["Annual Filing", "Quarterly Filing", "License Renewal", "Environmental Report", "Employment Report", "Safety Report", "Financial Disclosure", "Industry-Specific", "Amendment", "New Registration", "General"],
  },
  {
    subcategoryId: "conflict-of-interest",
    docKind: "form",
    noun: "Conflict of Interest Disclosure",
    purpose: "discloses a potential conflict of interest for review",
    extraFields: [f("nature_of_conflict", "Nature of Conflict", "textarea", false)],
    flavors: ["Financial Interest", "Family Relationship", "Outside Employment", "Board Membership", "Vendor Relationship", "Gift Disclosure", "Ownership Stake", "Consulting Arrangement", "Hiring Decision", "Procurement Decision", "General"],
    overrides: { subjectLabel: "Disclosed By", approverLabel: "Compliance Officer", detailsLabel: "Description" },
  },

  // ---------------- Sales & Marketing ----------------
  {
    subcategoryId: "proposals",
    docKind: "report",
    noun: "Sales Proposal",
    purpose: "presents a formal offer of products or services to a prospective client",
    extraFields: [f("client_name", "Client Name"), f("proposed_value", "Proposed Deal Value", "currency", false)],
    flavors: ["New Business", "Renewal", "Upsell", "Enterprise", "SMB", "RFP Response", "Partnership", "Pilot Program", "Multi-Year", "Custom Solution", "General"],
  },
  {
    subcategoryId: "quotes",
    docKind: "invoice",
    noun: "Price Quote",
    purpose: "provides a formal price quotation for goods or services",
    extraFields: [f("valid_until", "Valid Until", "date", false)],
    flavors: ["Standard", "Volume Discount", "Custom Configuration", "Rush Order", "Subscription", "One-Time", "Bundle", "Renewal", "Competitive", "International", "General"],
    overrides: { counterpartyLabel: "Prepared For", totalLabel: "Quoted Price" },
  },
  {
    subcategoryId: "campaign-briefs",
    docKind: "plan",
    noun: "Campaign Brief",
    purpose: "outlines the goals, audience, and plan for a marketing campaign",
    extraFields: [f("target_audience", "Target Audience", "textarea", false), f("budget", "Budget", "currency", false)],
    flavors: ["Product Launch", "Seasonal", "Social Media", "Email", "Paid Search", "Brand Awareness", "Event Marketing", "Content Marketing", "Partnership", "Rebrand", "General"],
    overrides: { objectivesLabel: "Campaign Objectives" },
  },
  {
    subcategoryId: "press-releases",
    docKind: "notice",
    noun: "Press Release",
    purpose: "announces newsworthy company information to the public and media",
    extraFields: [f("headline", "Headline")],
    flavors: ["Product Launch", "Funding Announcement", "Partnership", "Leadership Hire", "Award", "Milestone", "Event Announcement", "Acquisition", "Community Initiative", "Rebrand", "General"],
  },
  {
    subcategoryId: "sales-reports",
    docKind: "report",
    noun: "Sales Report",
    purpose: "reports on sales performance for a given period",
    extraFields: [f("total_revenue", "Total Revenue", "currency", false), f("region", "Region / Territory", "text", false)],
    flavors: ["Weekly", "Monthly", "Quarterly", "Regional", "Rep-Level", "Product-Line", "Pipeline", "Win/Loss", "Forecast", "Year-End", "General"],
  },
  {
    subcategoryId: "lead-gen-forms",
    docKind: "form",
    noun: "Lead Generation Form",
    purpose: "captures and qualifies a new sales lead",
    extraFields: [f("lead_source", "Lead Source", "select", true, { options: ["Website", "Referral", "Event", "Cold Outreach", "Paid Ad", "Partner", "Other"] }), f("interest_level", "Interest Level", "select", false, { options: ["Hot", "Warm", "Cold"] })],
    flavors: ["Website Inquiry", "Trade Show", "Referral", "Cold Outreach", "Webinar Signup", "Demo Request", "Partner Referral", "Content Download", "Event Follow-Up", "Inbound Call", "General"],
    overrides: { subjectLabel: "Lead Name", approverLabel: "Assigned Rep", detailsLabel: "Notes", includeDepartment: false },
  },
  {
    subcategoryId: "marketing-plans",
    docKind: "plan",
    noun: "Marketing Plan",
    purpose: "sets strategy, channels, and goals for a marketing period",
    extraFields: [f("target_market", "Target Market", "textarea", false), f("budget", "Budget", "currency", false)],
    flavors: ["Annual", "Quarterly", "Product Launch", "Regional", "Digital-First", "Content Strategy", "Brand Strategy", "Growth", "Retention", "Event-Driven", "General"],
    overrides: { objectivesLabel: "Goals" },
  },
  {
    subcategoryId: "case-studies",
    docKind: "report",
    noun: "Case Study",
    purpose: "showcases a customer's success story for marketing use",
    extraFields: [f("client_name", "Client Name"), f("results", "Key Results", "textarea", false)],
    flavors: ["Enterprise Customer", "SMB Customer", "Industry-Specific", "ROI-Focused", "Product Feature", "Turnaround Story", "Partnership", "Long-Term Client", "Quick Win", "Video-Companion", "General"],
    overrides: { includePeriod: false },
  },
  {
    subcategoryId: "social-media-calendars",
    docKind: "plan",
    noun: "Social Media Content Calendar",
    purpose: "plans social media posts and themes across a time period",
    extraFields: [f("platforms", "Platforms", "text", false, { placeholder: "e.g. Instagram, LinkedIn" })],
    flavors: ["Monthly", "Weekly", "Product Launch", "Holiday", "Campaign-Specific", "Influencer Collaboration", "User-Generated Content", "Event Coverage", "Evergreen Content", "Paid Promotion", "General"],
    overrides: { objectivesLabel: "Content Themes" },
  },
  {
    subcategoryId: "client-onboarding-sales",
    docKind: "checklist",
    noun: "Client Onboarding Checklist",
    purpose: "walks a new client through getting started after signing",
    extraFields: [f("client_name", "Client Name")],
    flavors: ["Enterprise", "SMB", "Self-Serve", "Managed Service", "Trial-to-Paid", "Multi-Location", "International", "Reseller", "Renewal Transition", "White-Glove", "General"],
  },

  // ---------------- Project Management ----------------
  {
    subcategoryId: "project-charters",
    docKind: "plan",
    noun: "Project Charter",
    purpose: "formally authorizes a project and defines its scope and sponsor",
    extraFields: [f("sponsor", "Project Sponsor"), f("budget", "Estimated Budget", "currency", false)],
    flavors: ["Internal Initiative", "Client-Facing", "IT System", "Product Launch", "Process Improvement", "Facilities", "Research", "Compliance", "Cross-Functional", "Pilot", "General"],
    overrides: { objectivesLabel: "Project Objectives" },
  },
  {
    subcategoryId: "status-reports",
    docKind: "report",
    noun: "Project Status Report",
    purpose: "reports progress, risks, and next steps for an ongoing project",
    extraFields: [f("overall_status", "Overall Status", "select", true, { options: ["On Track", "At Risk", "Delayed", "Completed"] })],
    flavors: ["Weekly", "Biweekly", "Monthly", "Executive Summary", "Client-Facing", "Sprint-Based", "Milestone", "Steering Committee", "Post-Phase", "Year-End", "General"],
  },
  {
    subcategoryId: "risk-logs",
    docKind: "log",
    noun: "Risk Log",
    purpose: "tracks identified project risks and mitigation plans",
    extraFields: [f("risk_owner", "Risk Owner", "text", false)],
    flavors: ["Weekly", "Sprint-Based", "Vendor-Related", "Technical", "Schedule", "Budget", "Compliance", "Resourcing", "External", "Program-Level", "General"],
    overrides: { entriesLabel: "Risk Entries" },
  },
  {
    subcategoryId: "meeting-minutes",
    docKind: "memo",
    noun: "Meeting Minutes",
    purpose: "records the discussion, decisions, and action items from a meeting",
    extraFields: [f("attendees", "Attendees", "textarea", false), f("action_items", "Action Items", "textarea", false)],
    flavors: ["Team Standup", "Steering Committee", "Client Meeting", "Retrospective", "Planning Session", "Kickoff", "Vendor Meeting", "Board Meeting", "Ad Hoc", "One-on-One", "General"],
  },
  {
    subcategoryId: "raci-charts",
    docKind: "log",
    noun: "RACI Chart",
    purpose: "assigns Responsible, Accountable, Consulted, and Informed roles across project tasks",
    extraFields: [f("project_name", "Project Name")],
    flavors: ["Software Project", "Marketing Campaign", "Product Launch", "Process Change", "Cross-Team Initiative", "Vendor Engagement", "Compliance Project", "Event Planning", "Migration Project", "Org Change", "General"],
    overrides: { entriesLabel: "Task / Role Assignments" },
  },
  {
    subcategoryId: "project-plans",
    docKind: "plan",
    noun: "Project Plan",
    purpose: "lays out the timeline, milestones, and resources for a project",
    extraFields: [f("start_date", "Start Date", "date"), f("end_date", "End Date", "date", false)],
    flavors: ["Software Development", "Marketing Campaign", "Construction", "Event", "Product Launch", "Research", "Migration", "Process Improvement", "Facilities", "Rollout", "General"],
  },
  {
    subcategoryId: "change-requests-pm",
    docKind: "form",
    noun: "Project Change Request",
    purpose: "requests a change to project scope, schedule, or budget",
    extraFields: [f("impact", "Impact on Scope/Schedule/Budget", "textarea", false)],
    flavors: ["Scope Increase", "Schedule Extension", "Budget Increase", "Resource Change", "Requirement Change", "Vendor Change", "De-Scoping", "Priority Change", "Technical Change", "Emergency", "General"],
    overrides: { subjectLabel: "Requested By", approverLabel: "Project Sponsor", detailsLabel: "Reason for Change" },
  },
  {
    subcategoryId: "issue-logs",
    docKind: "log",
    noun: "Issue Log",
    purpose: "tracks project issues and their resolution status",
    extraFields: [f("project_name", "Project Name", "text", false)],
    flavors: ["Weekly", "Sprint-Based", "Technical", "Vendor", "Resourcing", "Client-Reported", "Escalated", "Blocking", "Post-Launch", "Program-Level", "General"],
    overrides: { entriesLabel: "Issue Entries" },
  },
  {
    subcategoryId: "post-mortems",
    docKind: "report",
    noun: "Project Post-Mortem",
    purpose: "reviews what went well and what to improve after a project concludes",
    extraFields: [f("what_went_well", "What Went Well", "textarea", false), f("what_to_improve", "What To Improve", "textarea", false)],
    flavors: ["Successful Launch", "Missed Deadline", "Over Budget", "Incident Response", "Product Launch", "Sprint Retrospective", "Vendor Engagement", "Migration", "Cross-Team Project", "Client Project", "General"],
  },
  {
    subcategoryId: "resource-plans",
    docKind: "plan",
    noun: "Resource Allocation Plan",
    purpose: "plans how people and resources are assigned across a project or period",
    extraFields: [f("headcount", "Team Size / Headcount", "number", false)],
    flavors: ["Quarterly", "Project-Based", "Cross-Team", "Seasonal", "Contractor-Inclusive", "Multi-Project", "Capacity Planning", "Reorg", "New Team", "Scaling", "General"],
    overrides: { objectivesLabel: "Allocation Plan" },
  },

  // ---------------- IT & Technical ----------------
  {
    subcategoryId: "incident-reports-it",
    docKind: "form",
    noun: "IT Incident Report",
    purpose: "documents a technical incident, its impact, and resolution",
    extraFields: [f("severity", "Severity", "select", true, { options: ["Critical", "High", "Medium", "Low"] }), f("system_affected", "System Affected")],
    flavors: ["Server Outage", "Network Issue", "Security Breach", "Data Loss", "Application Crash", "Third-Party Outage", "Performance Degradation", "Failed Deployment", "Hardware Failure", "Access Issue", "General"],
    overrides: { subjectLabel: "Reported By", approverLabel: "IT Lead", detailsLabel: "Description & Resolution" },
  },
  {
    subcategoryId: "change-requests-it",
    docKind: "form",
    noun: "IT Change Request",
    purpose: "requests approval for a change to systems or infrastructure",
    extraFields: [f("system", "System / Service"), f("planned_date", "Planned Change Date", "date", false)],
    flavors: ["Software Update", "Infrastructure Change", "Configuration Change", "Security Patch", "Database Migration", "Network Change", "Access Policy Change", "Emergency Change", "Vendor-Driven", "Scheduled Maintenance", "General"],
    overrides: { subjectLabel: "Requested By", approverLabel: "Change Approver", detailsLabel: "Description of Change" },
  },
  {
    subcategoryId: "sops",
    docKind: "checklist",
    noun: "Standard Operating Procedure",
    purpose: "documents the step-by-step process for a recurring technical task",
    extraFields: [f("system_or_tool", "System / Tool", "text", false)],
    flavors: ["Deployment", "Backup", "Incident Response", "Onboarding a New System", "Access Provisioning", "Monitoring", "Patch Management", "Data Migration", "Disaster Recovery", "Vendor Escalation", "General"],
  },
  {
    subcategoryId: "access-requests",
    docKind: "form",
    noun: "Access Request Form",
    purpose: "requests access to a system, application, or facility",
    extraFields: [f("system_requested", "System / Resource"), f("access_level", "Access Level", "select", false, { options: ["Read-Only", "Standard", "Admin", "Temporary"] })],
    flavors: ["New Hire", "System Upgrade", "Temporary Access", "Contractor", "Admin Access", "Cross-Department", "Vendor Access", "Emergency Access", "Role Change", "Offboarding Revocation", "General"],
    overrides: { subjectLabel: "Requested For", approverLabel: "System Owner", detailsLabel: "Business Justification" },
  },
  {
    subcategoryId: "outage-notices",
    docKind: "notice",
    noun: "System Outage Notice",
    purpose: "communicates a planned or unplanned system outage to affected users",
    extraFields: [f("system_affected", "System Affected"), f("expected_resolution", "Expected Resolution", "text", false)],
    flavors: ["Planned Maintenance", "Unplanned Outage", "Partial Degradation", "Third-Party Outage", "Network Outage", "Scheduled Upgrade", "Data Center Migration", "Security Patch Window", "Recurring Maintenance", "Emergency Outage", "General"],
  },
  {
    subcategoryId: "bug-reports",
    docKind: "form",
    noun: "Bug Report",
    purpose: "documents a software defect for the engineering team to triage",
    extraFields: [f("severity", "Severity", "select", true, { options: ["Critical", "High", "Medium", "Low"] }), f("steps_to_reproduce", "Steps to Reproduce", "textarea", false)],
    flavors: ["UI Bug", "Crash", "Performance Issue", "Data Integrity", "Security Vulnerability", "Regression", "Mobile-Specific", "Browser-Specific", "API Error", "Third-Party Integration", "General"],
    overrides: { subjectLabel: "Reported By", approverLabel: "Engineering Lead", detailsLabel: "Description" },
  },
  {
    subcategoryId: "system-documentation",
    docKind: "report",
    noun: "System Documentation",
    purpose: "provides reference documentation for an internal system or process",
    extraFields: [f("system_name", "System Name"), f("owner_team", "Owner Team", "text", false)],
    flavors: ["Architecture Overview", "API Reference", "Setup Guide", "Troubleshooting Guide", "Integration Guide", "Data Flow", "Runbook", "Configuration Reference", "Onboarding Guide", "Deprecation Notice", "General"],
  },
  {
    subcategoryId: "backup-recovery",
    docKind: "plan",
    noun: "Backup & Recovery Plan",
    purpose: "defines how data and systems are backed up and restored in a disaster",
    extraFields: [f("system_covered", "System(s) Covered")],
    flavors: ["Database", "File Server", "Full Infrastructure", "Application-Specific", "Cloud Environment", "Disaster Recovery", "Ransomware Response", "Regional Failover", "Quarterly Test", "Vendor-Managed", "General"],
    overrides: { objectivesLabel: "Backup & Recovery Strategy" },
  },
  {
    subcategoryId: "software-requests",
    docKind: "form",
    noun: "Software Request Form",
    purpose: "requests approval to purchase or install new software",
    extraFields: [f("software_name", "Software Name"), f("estimated_cost", "Estimated Cost", "currency", false)],
    flavors: ["New Purchase", "License Renewal", "Upgrade", "Trial Request", "Open Source Approval", "Team-Wide Rollout", "Single-User", "Vendor Replacement", "Free Tool", "Security-Sensitive", "General"],
    overrides: { subjectLabel: "Requested By", approverLabel: "IT Approver", detailsLabel: "Business Justification" },
  },
  {
    subcategoryId: "security-reports",
    docKind: "form",
    noun: "Security Incident Report",
    purpose: "documents a security-related incident and the response taken",
    extraFields: [f("incident_type", "Incident Type", "select", true, { options: ["Phishing", "Malware", "Unauthorized Access", "Data Leak", "Physical Security", "Other"] }), f("severity", "Severity", "select", true, { options: ["Critical", "High", "Medium", "Low"] })],
    flavors: ["Phishing Attempt", "Malware Detection", "Unauthorized Access", "Data Leak", "Lost Device", "Insider Threat", "Physical Security", "Vendor Breach", "Credential Compromise", "Policy Violation", "General"],
    overrides: { subjectLabel: "Reported By", approverLabel: "Security Lead", detailsLabel: "Description & Response" },
  },

  // ---------------- Customer Service ----------------
  {
    subcategoryId: "complaint-responses",
    docKind: "letter",
    noun: "Complaint Response Letter",
    purpose: "formally responds to a customer complaint",
    extraFields: [f("complaint_summary", "Complaint Summary", "textarea", false)],
    flavors: ["Product Issue", "Service Delay", "Billing Error", "Staff Conduct", "Quality Issue", "Shipping Problem", "Refund Dispute", "Repeat Complaint", "Escalated", "Social Media Complaint", "General"],
  },
  {
    subcategoryId: "refund-forms",
    docKind: "form",
    noun: "Refund & Return Form",
    purpose: "processes a customer refund or return request",
    extraFields: [f("order_number", "Order Number"), f("refund_amount", "Refund Amount", "currency")],
    flavors: ["Full Refund", "Partial Refund", "Store Credit", "Exchange", "Defective Item", "Wrong Item Shipped", "Late Delivery", "Buyer's Remorse", "Warranty-Related", "Subscription Cancellation", "General"],
    overrides: { subjectLabel: "Customer Name", approverLabel: "Support Rep", detailsLabel: "Reason for Refund", includeDepartment: false },
  },
  {
    subcategoryId: "satisfaction-surveys",
    docKind: "form",
    noun: "Customer Satisfaction Survey",
    purpose: "gathers structured feedback on a customer's experience",
    extraFields: [f("satisfaction_rating", "Overall Satisfaction", "select", true, { options: ["Very Satisfied", "Satisfied", "Neutral", "Dissatisfied", "Very Dissatisfied"] })],
    flavors: ["Post-Purchase", "Post-Support Interaction", "Onboarding", "Annual", "NPS-Style", "Event Feedback", "Product Feedback", "Cancellation Survey", "Renewal", "In-App", "General"],
    overrides: { subjectLabel: "Customer Name", approverLabel: "Reviewed By", detailsLabel: "Comments", includeDepartment: false },
  },
  {
    subcategoryId: "escalation-notes",
    docKind: "memo",
    noun: "Escalation Note",
    purpose: "escalates a customer issue internally for higher-level handling",
    extraFields: [f("customer_name", "Customer Name"), f("urgency", "Urgency", "select", false, { options: ["Low", "Medium", "High", "Critical"] })],
    flavors: ["Billing Dispute", "VIP Customer", "Repeat Issue", "Legal Threat", "Social Media Escalation", "Technical Escalation", "Refund Dispute", "Contract Issue", "Safety Concern", "Executive Complaint", "General"],
  },
  {
    subcategoryId: "service-tickets",
    docKind: "log",
    noun: "Service Ticket Summary",
    purpose: "summarizes a customer support ticket and its resolution",
    extraFields: [f("ticket_number", "Ticket Number", "text", false), f("customer_name", "Customer Name")],
    flavors: ["Technical Support", "Billing Inquiry", "Account Access", "Product Question", "Bug Report", "Feature Request", "Complaint", "Onboarding Help", "Cancellation Request", "General Inquiry", "General"],
    overrides: { entriesLabel: "Resolution Notes" },
  },
  {
    subcategoryId: "apology-letters",
    docKind: "letter",
    noun: "Apology Letter",
    purpose: "formally apologizes to a customer for a service failure",
    extraFields: [f("issue_summary", "What Went Wrong", "textarea", false)],
    flavors: ["Shipping Delay", "Service Outage", "Billing Error", "Product Defect", "Staff Conduct", "Data Issue", "Cancelled Order", "Miscommunication", "Repeat Issue", "Public Incident", "General"],
  },
  {
    subcategoryId: "warranty-claims",
    docKind: "form",
    noun: "Warranty Claim Form",
    purpose: "processes a customer's warranty claim for a defective product",
    extraFields: [f("product_name", "Product Name"), f("purchase_date", "Purchase Date", "date", false)],
    flavors: ["Manufacturing Defect", "Malfunction", "Accessory Failure", "Extended Warranty", "Replacement Request", "Repair Request", "Recall-Related", "Out-of-Warranty Exception", "Bulk Order", "International", "General"],
    overrides: { subjectLabel: "Customer Name", approverLabel: "Support Rep", detailsLabel: "Description of Issue", includeDepartment: false },
  },
  {
    subcategoryId: "customer-onboarding-cs",
    docKind: "checklist",
    noun: "Customer Onboarding Guide",
    purpose: "helps a new customer get started with the product or service",
    extraFields: [f("customer_name", "Customer Name", "text", false)],
    flavors: ["Self-Serve", "Guided Setup", "Enterprise", "Free Trial", "Mobile App", "Subscription Service", "Reseller Customer", "Migration from Competitor", "Family/Multi-User", "White-Glove", "General"],
  },
  {
    subcategoryId: "faq-documents",
    docKind: "report",
    noun: "FAQ Document",
    purpose: "answers frequently asked customer questions in one reference",
    extraFields: [f("topic_area", "Topic Area")],
    flavors: ["Billing", "Shipping", "Returns", "Account Setup", "Product Usage", "Troubleshooting", "Subscription", "Security & Privacy", "Pricing", "General Support", "General"],
    overrides: { includePeriod: false },
  },
  {
    subcategoryId: "feedback-forms",
    docKind: "form",
    noun: "Feedback Collection Form",
    purpose: "collects general customer feedback about the product or experience",
    extraFields: [f("feedback_category", "Category", "select", false, { options: ["Product", "Service", "Website", "Pricing", "Support", "Other"] })],
    flavors: ["Product Feedback", "Website Feedback", "Support Experience", "Feature Request", "Pricing Feedback", "Event Feedback", "Beta Tester", "Churned Customer", "Long-Time Customer", "Anonymous", "General"],
    overrides: { subjectLabel: "Customer Name (Optional)", approverLabel: "Reviewed By", detailsLabel: "Feedback", includeDepartment: false },
  },

  // ---------------- Procurement & Vendor Management ----------------
  {
    subcategoryId: "rfqs",
    docKind: "invoice",
    noun: "Request for Quotation",
    purpose: "requests pricing from a vendor for specified goods or services",
    extraFields: [f("response_deadline", "Response Deadline", "date", false)],
    flavors: ["Standard", "Sole-Source", "Multi-Vendor", "Equipment", "Services", "Bulk Order", "Recurring Supply", "International", "Rush", "Annual Contract", "General"],
    overrides: { counterpartyLabel: "Vendor", totalLabel: "Estimated Value", includeDueDate: false },
  },
  {
    subcategoryId: "rfps",
    docKind: "report",
    noun: "Request for Proposal",
    purpose: "solicits detailed proposals from vendors for a project or contract",
    extraFields: [f("project_scope", "Project Scope", "textarea", false), f("submission_deadline", "Submission Deadline", "date", false)],
    flavors: ["IT Services", "Construction", "Marketing Services", "Consulting", "Software Implementation", "Facilities", "Staffing", "Logistics", "Professional Services", "Multi-Year Contract", "General"],
  },
  {
    subcategoryId: "vendor-agreements",
    docKind: "contract",
    noun: "Vendor Agreement",
    purpose: "formalizes the terms of an ongoing relationship with a supplier",
    extraFields: [f("services_provided", "Services / Goods Provided", "textarea", false)],
    flavors: ["Supply Agreement", "Service Level Agreement", "Master Services Agreement", "Distribution Agreement", "Consulting Agreement", "Exclusive Vendor", "Preferred Vendor", "Trial Period", "Renewal", "Termination Notice Included", "General"],
    overrides: { partyALabel: "Company", partyBLabel: "Vendor" },
  },
  {
    subcategoryId: "po-forms",
    docKind: "invoice",
    noun: "Purchase Order Form",
    purpose: "provides a standardized form for ordering from an approved vendor",
    extraFields: [f("po_number", "PO Number", "text", false)],
    flavors: ["Standard", "Rush", "Recurring", "Blanket", "Services", "Capital Equipment", "International", "Drop-Ship", "Amendment", "Emergency", "General"],
    overrides: { counterpartyLabel: "Vendor", totalLabel: "Order Total" },
  },
  {
    subcategoryId: "supplier-evaluations",
    docKind: "report",
    noun: "Supplier Evaluation",
    purpose: "evaluates a supplier's performance against agreed criteria",
    extraFields: [f("supplier_name", "Supplier Name"), f("overall_score", "Overall Score", "select", false, { options: ["Excellent", "Good", "Fair", "Poor"] })],
    flavors: ["Annual Review", "Quarterly Review", "New Supplier Trial", "Quality Audit", "Delivery Performance", "Cost Competitiveness", "Compliance Review", "Renewal Decision", "Incident Follow-Up", "Strategic Partner", "General"],
  },
  {
    subcategoryId: "vendor-onboarding",
    docKind: "checklist",
    noun: "Vendor Onboarding Checklist",
    purpose: "walks a new vendor through setup and compliance requirements",
    extraFields: [f("vendor_name", "Vendor Name")],
    flavors: ["Standard", "International", "Sole Proprietor", "Large Enterprise", "Subcontractor", "IT Vendor", "Service Provider", "Recurring Supplier", "One-Time Vendor", "High-Risk Category", "General"],
  },
  {
    subcategoryId: "contract-renewals",
    docKind: "notice",
    noun: "Contract Renewal Notice",
    purpose: "notifies a vendor of an upcoming contract renewal decision",
    extraFields: [f("vendor_name", "Vendor Name"), f("renewal_date", "Renewal Date", "date", false)],
    flavors: ["Auto-Renewal Notice", "Renewal with Changes", "Non-Renewal Notice", "Early Renewal", "Price Increase Notice", "Multi-Year Renewal", "Trial Extension", "Renegotiation Request", "Termination Notice", "Renewal Confirmation", "General"],
  },
  {
    subcategoryId: "procurement-policies",
    docKind: "notice",
    noun: "Procurement Policy",
    purpose: "documents internal rules for purchasing and vendor selection",
    extraFields: [f("policy_owner", "Policy Owner", "text", false)],
    flavors: ["General Purchasing", "Competitive Bidding", "Sole-Source Justification", "Spend Approval Thresholds", "Vendor Selection Criteria", "Conflict of Interest", "Emergency Purchasing", "Sustainable Sourcing", "Small Business Preference", "International Sourcing", "General"],
  },
  {
    subcategoryId: "delivery-receipts",
    docKind: "log",
    noun: "Delivery & Receiving Record",
    purpose: "confirms receipt of goods delivered from a vendor",
    extraFields: [f("vendor_name", "Vendor Name"), f("po_number", "Related PO #", "text", false)],
    flavors: ["Standard Delivery", "Partial Shipment", "Damaged Goods", "Rush Delivery", "International Shipment", "Bulk Delivery", "Return-to-Vendor", "Backorder Fulfillment", "Drop-Ship Confirmation", "Discrepancy Noted", "General"],
    overrides: { entriesLabel: "Items Received" },
  },
  {
    subcategoryId: "vendor-complaints",
    docKind: "form",
    noun: "Vendor Performance Complaint",
    purpose: "formally documents a complaint about a vendor's performance",
    extraFields: [f("vendor_name", "Vendor Name"), f("issue_type", "Issue Type", "select", false, { options: ["Late Delivery", "Quality Issue", "Billing Error", "Poor Communication", "Contract Breach", "Other"] })],
    flavors: ["Late Delivery", "Quality Issue", "Billing Dispute", "Poor Communication", "Contract Breach", "Safety Concern", "Repeated Issue", "Service Failure", "Damaged Goods", "Unresponsive Vendor", "General"],
    overrides: { subjectLabel: "Reported By", approverLabel: "Procurement Manager", detailsLabel: "Description of Issue" },
  },

  // ---------------- Administrative & Office Operations ----------------
  {
    subcategoryId: "facility-requests",
    docKind: "form",
    noun: "Facility Request",
    purpose: "requests office space setup, repairs, or facility changes",
    extraFields: [f("location", "Location / Room", "text", false)],
    flavors: ["Repair Request", "New Setup", "Furniture Request", "Space Reconfiguration", "Cleaning Request", "Maintenance", "Signage", "Accessibility Accommodation", "Temperature/HVAC", "Security Update", "General"],
    overrides: { subjectLabel: "Requested By", approverLabel: "Facilities Manager", detailsLabel: "Description" },
  },
  {
    subcategoryId: "travel-forms",
    docKind: "form",
    noun: "Travel Request Form",
    purpose: "requests approval to book business travel",
    extraFields: [f("destination", "Destination"), f("travel_dates", "Travel Dates", "text", false)],
    flavors: ["Domestic", "International", "Client Visit", "Conference", "Training", "Team Off-Site", "Sales Trip", "Executive Travel", "Last-Minute", "Multi-City", "General"],
    overrides: { subjectLabel: "Traveler Name", approverLabel: "Manager", detailsLabel: "Purpose of Travel" },
  },
  {
    subcategoryId: "timesheets",
    docKind: "log",
    noun: "Timesheet",
    purpose: "records hours worked for a pay period",
    extraFields: [f("employee_name", "Employee Name")],
    flavors: ["Weekly", "Biweekly", "Monthly", "Hourly Staff", "Salaried Exempt", "Contractor", "Project-Based", "Overtime", "Remote Employee", "Multi-Project", "General"],
    overrides: { entriesLabel: "Hours Logged" },
  },
  {
    subcategoryId: "supply-requisitions",
    docKind: "form",
    noun: "Supply Requisition",
    purpose: "requests office supplies or small equipment",
    extraFields: [f("items_needed", "Items Needed", "textarea", false)],
    flavors: ["General Office Supplies", "Bulk Order", "Kitchen/Break Room", "IT Peripherals", "Furniture", "Cleaning Supplies", "Event Supplies", "Department-Specific", "Emergency Restock", "Recurring Order", "General"],
    overrides: { subjectLabel: "Requested By", approverLabel: "Office Manager", detailsLabel: "Notes" },
  },
  {
    subcategoryId: "visitor-logs",
    docKind: "log",
    noun: "Visitor Log",
    purpose: "records visitors entering and leaving the office",
    extraFields: [f("location", "Front Desk / Location", "text", false)],
    flavors: ["Front Desk", "Contractor Access", "Interview Candidates", "Vendor Visits", "Client Meetings", "Delivery Personnel", "Building Maintenance", "After-Hours Access", "Event Attendees", "Security Escort", "General"],
    overrides: { entriesLabel: "Visitor Entries" },
  },
  {
    subcategoryId: "meeting-room-bookings",
    docKind: "form",
    noun: "Meeting Room Booking",
    purpose: "reserves a meeting room or shared space",
    extraFields: [f("room_name", "Room / Space"), f("time_slot", "Date & Time", "text", false)],
    flavors: ["Internal Meeting", "Client Meeting", "Interview", "Training Session", "All-Hands", "Recurring Booking", "Video Conference Room", "Off-Hours", "Multi-Room Event", "Last-Minute", "General"],
    overrides: { subjectLabel: "Booked By", approverLabel: "Office Admin", detailsLabel: "Purpose" },
  },
  {
    subcategoryId: "mail-courier",
    docKind: "log",
    noun: "Mail & Courier Log",
    purpose: "tracks incoming and outgoing mail and courier packages",
    extraFields: [f("handled_by", "Handled By", "text", false)],
    flavors: ["Incoming Mail", "Outgoing Mail", "Courier Pickup", "Certified Mail", "International Shipment", "Package Delivery", "Signature-Required", "Interoffice Mail", "Bulk Mailing", "Return-to-Sender", "General"],
    overrides: { entriesLabel: "Mail / Package Entries" },
  },
  {
    subcategoryId: "equipment-checkout",
    docKind: "form",
    noun: "Equipment Checkout Form",
    purpose: "tracks company equipment checked out to an employee",
    extraFields: [f("equipment_item", "Equipment Item"), f("expected_return_date", "Expected Return Date", "date", false)],
    flavors: ["Laptop", "Projector", "Company Phone", "Camera Equipment", "Loaner Device", "Conference Equipment", "Tools", "Vehicle", "Badge/Access Card", "Temporary Equipment", "General"],
    overrides: { subjectLabel: "Checked Out By", approverLabel: "IT / Facilities", detailsLabel: "Condition Notes" },
  },
  {
    subcategoryId: "office-policies",
    docKind: "notice",
    noun: "Office Policy Notice",
    purpose: "communicates a general office operations policy to staff",
    extraFields: [f("policy_owner", "Policy Owner", "text", false)],
    flavors: ["Kitchen Etiquette", "Desk Booking", "Parking", "Guest Policy", "Noise Policy", "Dress Code", "Recycling & Sustainability", "Building Access Hours", "Package Handling", "Shared Equipment Use", "General"],
  },
  {
    subcategoryId: "emergency-procedures",
    docKind: "plan",
    noun: "Emergency Procedure",
    purpose: "outlines the steps staff should take in an emergency",
    extraFields: [f("emergency_type", "Emergency Type", "select", false, { options: ["Fire", "Severe Weather", "Medical", "Security Threat", "Power Outage", "Other"] })],
    flavors: ["Fire Evacuation", "Severe Weather", "Medical Emergency", "Active Threat", "Power Outage", "Earthquake", "Bomb Threat", "Chemical Spill", "IT/Cyber Emergency", "Building Lockdown", "General"],
    overrides: { objectivesLabel: "Procedure Steps" },
  },
];
